Equal-Vote/bettervoting

- .gitignore
- domain_model/Ballot.ts
- domain_model/Candidate.ts
- domain_model/Credentials.ts
- domain_model/Election.ts
- domain_model/Email.ts
- domain_model/NewPassword.ts
- domain_model/Poll.ts
- domain_model/Score.ts
- domain_model/Uid.ts
- domain_model/Vote.ts
Adding basic data types for a domain model.
> Basic data types for domain model

- backend/src/Util.ts
- backend/src/index.ts
- backend/src/test/DBTest.ts
- backend/src/test/DemoPGStore.ts
- backend/src/test/TempTestSuite.ts
- backend/tsconfig.json
Adds a demo postgres database.
Runs a test that just updates a counter.  Wait for the instance to reset (or force it to rebuild) and note that the counter is persisted.
REQUIRES that the Postgres db be setup on the heroku app:
https://devcenter.heroku.com/articles/heroku-postgresql
```
heroku addons:create heroku-postgresql:hobby-dev
```
> demo of a working pg database

- frontend/src/App.tsx
- frontend/src/components/Header.js
The functionality works the same on my local version except I'm not referencing localhost anymore
fixes #7
> Fix login invalid login path when deployed to heroku

- backend/src/index.ts
- domain_model/Poll.ts
- frontend/src/components/AddCandidate.tsx
- frontend/src/components/AddElection.tsx
- frontend/src/components/Button.tsx
- frontend/src/components/Results.js
- frontend/src/index.css
Start and stop times aren't used by back end yet, but we can set them.
> Adding a start/stop times, voting method, and number of winners

- backend/src/Controllers/elections.controllers.ts
- backend/src/Models/Ballots.ts
- backend/src/Models/Elections.ts
- backend/src/Routes/debug.routes.js
- backend/src/Routes/elections.routes.js
- backend/src/index.ts
Moved routes and other functions into their own folders and files.
> Adding more structure to back end

- backend/package-lock.json
- backend/package.json
- backend/src/Controllers/ballots.controllers.ts
- backend/src/Controllers/elections.controllers.ts
- backend/src/Controllers/voterRolls.controller.ts
- backend/src/Models/VoterRolls.ts
- backend/src/Routes/debug.routes.js
- domain_model/VoterRoll.ts
Initial structure for voter rolls and some debug methods
In the market for better names for voter rolls and entries.
> Adding voter roll database table

- backend/src/index.ts
We're planning to standardize the PR deployment URLs, this will allow us to continue testing auth within PRs
> Update redirect URIs

- docs/require_vs_import.md
I spent a while digging into this, so I figured I'd share my findings in one place
> Add write up on the difference between require and import

- backend/src/Controllers/ballots.controllers.ts
- backend/src/Controllers/elections.controllers.ts
- backend/src/Controllers/voterRolls.controller.ts
- backend/src/Routes/elections.routes.js
- backend/src/test/app.test.ts
- backend/src/test/testInputs.ts
- frontend/src/components/ElectionHome.tsx
Checks to see if election state needs to update when retrieved.
Only allows edits while in draft state
Only allows ballots to be submitted in open state
Adds finalize button on voter home page (Doesn't check if owner of election though)
Updated tests to use id of correct test election, not a hard coded id. Should make it easier to add more tests.
> Adding election state transitions and checks

- backend/src/Controllers/auth.controllers.ts
- backend/src/Controllers/ballots.controllers.ts
- backend/src/Controllers/elections.controllers.ts
- backend/src/Controllers/voterRolls.controller.ts
- backend/src/Models/Elections.ts
- backend/src/Routes/elections.routes.js
- backend/src/auth/permissions.ts
- backend/src/auth/roles.ts
- domain_model/Election.ts
Adding permissions based on owner, admin, and auditor status
Adding a few more routes to backend.
> Adding permissions and more routes

- frontend/src/components/Election.tsx
mysteriously disappeared during a merge.
> Readding Election componenet

- backend/src/Controllers/ballots.controllers.ts
- backend/src/Controllers/elections.controllers.ts
- backend/src/Controllers/voterRolls.controller.ts
- backend/src/ServiceLocator.ts
using Service Locator to provide all DBs. 
Will be needed for controllers that interact with multiple DBs (so they are all working on the same DB instance)
> using Service Locator to provide all DBs.  

- backend/package-lock.json
- backend/package.json
- backend/src/Controllers/addElectionRollController.ts
- backend/src/Controllers/auth.controllers.ts
- backend/src/Controllers/changeElectionRollController.ts
- backend/src/Controllers/controllerUtils.ts
- backend/src/Controllers/createElectionController.ts
- backend/src/Controllers/deleteElectionController.ts
- backend/src/Controllers/editElectionRollController.ts
- backend/src/Controllers/elections.controllers.ts
- backend/src/Controllers/getElectionRollController.ts
- backend/src/Controllers/voterRolls.controller.ts
- backend/src/Routes/elections.routes.js
- backend/src/app.ts
- backend/src/errorCatchMiddleware.ts
First pass at refactoring the voter roll controllers and the delete election controllers. They didn't require multiple databases, but I have a few TODOs for after Scott's PR is merged. I combined a few of them in the same file where it looks like it made sense.
> refactoring voter roll and delete election controllers

- backend/src/Models/ElectionRolls.ts
- frontend/src/components/AddCandidate.tsx
- frontend/src/components/ElectionForm.tsx
Moved election settings into an expandable section, added text field to quickly add candidates instead of the button which opened the more detailed form.
Also fixed error in election roll database that returned an empty array instead of null
https://user-images.githubusercontent.com/41272412/183326354-7c56ee2f-58dc-4343-a166-2e3a374c75be.mp4
> Election form refactor

- backend/src/Models/ElectionRolls.ts
- backend/src/Routes/debug.routes.js
- backend/src/test/EmailTest.js
- frontend/src/components/ElectionForm.tsx
- frontend/src/components/VotePage.tsx
Minor changes, going to merge it real quick to get heroku app running again
> Updating a few old id formats that were missed

- docs/setup_locally.md
- frontend/sample.env
Fix for the issue Scott is having starting the frontend.  This is a much more minimal change than in the npm-audit PR, so will abandon that one.
> fix for frontend startup issue

- frontend/src/App.tsx
- frontend/src/components/DebugPage.tsx
Adding debug page to frontend.  Now just lets you override the login token with a JWT.  To bypass Keycloak if necessary.
> adding frontend debug page

- backend/src/Controllers/finalizeElectionController.ts
- backend/src/Controllers/voterRolls.controller.ts
- backend/src/Routes/elections.routes.js
- backend/src/Services/Email/__mocks__/EmailService.ts
- backend/src/test/TestHelper.ts
- backend/src/test/finalizeElection.test.ts
- backend/src/test/testInputs.ts
Creates finalize election controller and test. Currently test helper can't detect sent emails but can see sent emails when console logged. Tried importing service helper and importing mock service directly.
> Refactor finalize route

- backend/src/Controllers/castVoteController.ts
- backend/src/Controllers/finalizeElectionController.ts
- backend/src/Services/Email/EmailTemplates.ts
Adds ballot receipt to voters who are logged in. 
Receipt email contains ballot ID and link to verify ballot in front end that currently does not exist, needs to be added.
> Adding ballot receipts

- backend/src/Controllers/elections.controllers.ts
- backend/src/Controllers/getElectionsController.ts
- backend/src/Models/Elections.ts
- backend/src/Routes/elections.routes.js
- backend/src/Services/Account/AccountService.ts
- backend/src/Services/Account/AccountServiceUtils.ts
- backend/src/Services/Account/__mocks__/AccountService.ts
- backend/src/test/customAuthKey.test.ts
- domain_model/Election.ts
adds custom auth key field to an election.
when present, will use this key to authenticate users acting on the election, instead of the main app key
> optional custom auth key for election

- backend/src/Models/Elections.ts
- backend/src/Services/Account/AccountService.ts
- backend/src/Services/Account/__mocks__/AccountService.ts
- frontend/src/authSession.js
keycloak jwt verification needs public key, not private
fixing election model to include auth_key
> Fixing jst verification, fixing election model

- frontend/src/components/AddCandidate.tsx
- frontend/src/components/AddElection.tsx
- frontend/src/components/Admin.tsx
- frontend/src/components/DuplicateElection.tsx
- frontend/src/components/EditElection.tsx
- frontend/src/components/EditElectionRoll.tsx
- frontend/src/components/Election.tsx
- frontend/src/components/ElectionForm.tsx
- frontend/src/components/ElectionHome.tsx
- frontend/src/components/Sandbox.tsx
- frontend/src/components/StarBallot.js
- frontend/src/components/StarBallotView.js
- frontend/src/components/VotePage.tsx
- frontend/src/components/VoterAuth.tsx
- frontend/src/useFetch.js
- Fixing navigation after submitting election to route to new election page instead of home page.
- Disabling submit buttons while waiting for requests, displaying submitting message while waiting.
- Refreshes voter auth after voting so it correctly shows that voter has voted.
- Removes unused imports.
- Added data as output of usefetch.makerequest function in addition to setting data state so it can be used immediately without waiting for state change.
- Moved submit ballot button to top component, should make it easier to have multiple ballots.
> Front end cleanup

- backend/src/Controllers/editElectionController.ts
- backend/src/Controllers/editElectionRolesController.ts
- backend/src/Controllers/elections.controllers.ts
- backend/src/Routes/elections.routes.js
- domain_model/permissions.ts
- frontend/package-lock.json
- frontend/src/components/Election/Admin/Admin.tsx
- frontend/src/components/Election/Admin/EditElectionRoll.tsx
- frontend/src/components/Election/Admin/EditRoles.tsx
- frontend/src/components/Election/Admin/ViewElectionRolls.tsx
- frontend/src/components/Election/Election.tsx
- frontend/src/components/Election/ElectionHome.tsx
- frontend/src/components/Election/ShareButton.tsx
- frontend/src/components/Election/Sidebar.tsx
- frontend/src/components/Election/Voting/StarBallotView.js
- frontend/src/components/Election/Voting/Thanks.tsx
- frontend/src/components/Election/Voting/VotePage.tsx
- frontend/src/components/ElectionForm/Settings.tsx
- frontend/src/components/PermissionHandler.tsx
Built on #186 
Displays descriptions and bios with new lines characters correctly, before they'd be shown as one continuous line
Fixes #153
> Description new lines

- backend/src/Controllers/editElectionController.ts
- backend/src/Controllers/editElectionRolesController.ts
- backend/src/Controllers/elections.controllers.ts
- backend/src/Routes/elections.routes.js
- domain_model/permissions.ts
- frontend/package-lock.json
- frontend/src/components/Election/Admin/Admin.tsx
- frontend/src/components/Election/Admin/EditElectionRoll.tsx
- frontend/src/components/Election/Admin/EditRoles.tsx
- frontend/src/components/Election/Admin/ViewElectionRolls.tsx
- frontend/src/components/Election/Election.tsx
- frontend/src/components/Election/ElectionHome.tsx
- frontend/src/components/Election/ShareButton.tsx
- frontend/src/components/Election/Sidebar.tsx
- frontend/src/components/Election/Voting/Thanks.tsx
- frontend/src/components/Election/Voting/VotePage.tsx
- frontend/src/components/ElectionForm/Settings.tsx
- frontend/src/components/PermissionHandler.tsx
> Time bug fix

- backend/sample.env
- backend/src/Services/Account/AccountService.ts
- backend/src/Services/Account/AccountServiceUtils.ts
- backend/src/Services/Account/__mocks__/AccountService.ts
- backend/src/Services/Email/EmailTemplates.ts
- backend/src/app.ts
- backend/src/test/TestHelper.ts
- backend/src/test/createElection.test.ts
- backend/src/test/customAuthKey.test.ts
- backend/src/test/editElection.test.ts
- backend/src/test/precinctElection.test.ts
- frontend/src/components/Election/Admin/Admin.tsx
- frontend/src/components/Election/Admin/ViewBallot.tsx
- frontend/src/components/Election/Admin/ViewBallots.tsx
- frontend/src/components/Election/ElectionHome.tsx
- frontend/src/components/Election/ShareButton.tsx
- frontend/src/components/Election/Sidebar.tsx
- frontend/src/components/Election/Voting/StarBallotView.js
- frontend/src/components/Election/Voting/Thanks.tsx
- frontend/src/components/LandingPage.tsx
- frontend/src/components/styles.js
Some of the tests were failing due to older updates, updated tests and code to fix issue. This was mostly due to the update with custom tokens and being able to submit an election without a token. Now, we only check the token if one is provided, if the token is invalid it throws an error, and we use a separate token "custom_id_token" so custom tokens won't be checked against the keycloak key and won't throw an error.
Added a basic ballot admin page that can be used to see list of ballots and open each ballot to see votes and history.
> Test fixes, token validation, ballot admin page

- backend/src/Controllers/uploadImageController.ts
Guess AWS docs where written for windows.
> fixing case on import

- frontend/src/components/ElectionForm/ElectionDetails.tsx
- frontend/src/components/ElectionForm/ElectionForm.tsx
- frontend/src/components/ElectionForm/Races.tsx
- frontend/src/components/ElectionForm/Settings.tsx
Adding input validation to some parts of the election creation form. I looked into a few different ways to do this and this seemed to be the least annoying way to do it, but still ended up with things getting moved around in weird ways. Each page does it's own validation, so I had to move the back, next, and submit buttons into the different page components so they could trigger the validation first.
> Adding input validation

- backend/sample.env
- docs/setup_locally.md
I hit some issues setting up my environment after being away for a while
I updated the sample.env and troubleshooting accordingly
> Update sample.env and trouble shooting docs

- backend/src/Controllers/getElectionsController.ts
- backend/src/Models/ElectionRolls.ts
- backend/src/Models/Elections.ts
- domain_model/Election.ts
- frontend/src/components/Election/Admin/Admin.tsx
- frontend/src/components/Election/Admin/AdminHome.tsx
- frontend/src/components/Election/Admin/EditRoles.tsx
- frontend/src/components/Election/Admin/ViewBallot.tsx
- frontend/src/components/Election/Election.tsx
- frontend/src/components/Election/ElectionHome.tsx
- frontend/src/components/Election/Sidebar.tsx
- frontend/src/components/ElectionForm/AddElection.tsx
- frontend/src/components/ElectionForm/EditElection.tsx
- frontend/src/components/ElectionForm/QuickPoll.tsx
- frontend/src/components/ElectionForm/Races.tsx
- frontend/src/components/ElectionForm/Settings.tsx
- frontend/src/components/Elections.tsx
- frontend/src/components/Header.js
- frontend/src/components/LandingPage.tsx
- frontend/src/components/styles.js
- frontend/src/theme.js
- Adding admin home page that makes it more clear what user can and can't do and what next steps are, could use better styling. Also could be simplified with components. I mostly copy and pasted the same code over and over.
- Adding check to prevent duplicate candidate names
- Making button and header texts bold for better readability 
- Updating My Elections page with table view of elections user manages or can vote in. This involved changing the query filter as it was vulnerable to SQL injection
> Misc. features and bug fixes

- backend/src/Controllers/addElectionRollController.ts
- backend/src/Controllers/voterRollUtils.ts
- Prevent duplicate voters from being added from add voters page. This was done by just grabbing all voter rolls and searching for duplicates, could be improved by adding a dedicated database query
- No longer search for existing voter roll if no voter authentication is specified, was causing invalid sql queries
> Voter roll bug fixes

- backend/src/Controllers/getElectionResultsController.ts
- backend/src/Controllers/sandboxController.ts
- backend/src/Controllers/voterRollUtils.ts
- backend/src/Tabulators/IRV.ts
- backend/src/Tabulators/ITabulators.ts
- backend/src/Tabulators/RankedRobin.ts
- backend/src/Tabulators/Star.ts
- backend/src/Tabulators/VotingMethodSelecter.ts
- frontend/src/components/Election/Results/Results.js
- frontend/src/components/ElectionForm/Races.tsx
- frontend/src/components/Sandbox.tsx
Adding basic single winner IRV tabulator for running elections comparing different voting methods, not to be recommended for general use.
> Adding basic single winner IRV tabulator for running comparison elections

- frontend/src/components/Election/Voting/BallotSelector.js
- frontend/src/components/Election/Voting/GenericBallotView.js
- frontend/src/components/Election/Voting/PluralityBallotView.js
- frontend/src/components/Election/Voting/StarBallotView.js
- frontend/src/components/ElectionForm/Races.tsx
⚠️NOTE: Highly recommend reviewing the individual commits instead of the code diff. They're much easier to follow
This commit does the following
* Moves the StarBallotView into a GenericBallotView
* Recreates StarBallotView to leverage GenericBallotView
* Creates PluralityBallotView which also leverages GenericBallotView
I've got more more PRs coming for IRV and approval ;)
> Add plurality ballot support

- frontend/src/components/Election/Voting/Thanks.tsx
Removed paper border, moved donate button to link in text, added ballot submitted icon
> Small change to thanks for voting page

- frontend/package-lock.json
- frontend/package.json
- frontend/public/index.html
- frontend/src/components/Election/Voting/GenericBallotView.js
- frontend/src/components/Election/Voting/PluralityBallotView.js
- frontend/src/components/Election/Voting/StarBallotView.js
- frontend/src/index.css
Tweaked ballot to be closer to the target ballot
> Add stars to the ballot

- frontend/src/components/LandingPage.tsx
Adding link to equal.vote
#182
> Adding link to equal.vote

- backend/src/Tabulators/Approval.ts
- backend/src/Tabulators/IRV.ts
- backend/src/Tabulators/Plurality.ts
- frontend/src/components/Election/Results/Results.js
- frontend/src/components/Sandbox.tsx
Some quick fixes to some tabulator bugs so that they'll work, but still need some more refactoring and unit tests.
Adding some basic results pages for other voting methods.
Approval
Plurality
IRV
> Results pages and tabulator bug fixes

- frontend/src/components/Election/Voting/ApprovalBallotView.js
- frontend/src/components/Election/Voting/BallotSelector.js
- frontend/src/components/Election/Voting/GenericBallotView.js
- frontend/src/components/Election/Voting/RankedBallotView.js
- frontend/src/components/Election/Voting/StarBallotView.js
- frontend/src/components/Election/Voting/VotePage.tsx
- frontend/src/components/ElectionForm/Races.tsx
- frontend/src/index.css
Add ranked ballots and approval ballots
> Add Ranked Ballots and Approval Ballots

- frontend/src/components/Election/Voting/ApprovalBallotView.js
- frontend/src/components/Election/Voting/BallotPageSelector.js
- frontend/src/components/Election/Voting/GenericBallotView.js
- frontend/src/components/Election/Voting/PluralityBallotView.js
- frontend/src/components/Election/Voting/RankedBallotView.js
- frontend/src/components/Election/Voting/StarBallotView.js
- frontend/src/components/Election/Voting/VotePage.tsx
Randomizes order of candidates on ballot by default, will add setting in the future.
This is done by adding the candidate's scores to the candidate object instead of being held in a separate array. Then the array of candidates gets shuffled. When the ballot is submitted the scores get resorted into the correct order for tabulation.
This also opens up the potential to allow voters to sort candidates by score and get a better visual sense of how they've scored everyone.
> Random candidate order

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Election/Admin/ViewBallots.tsx
Adds link in ballot page to download csv of ballot data. Data includes just ballot ids and scores. Currently only works for just one race.
> Ballot data csv

- frontend/src/components/Election/Voting/GenericBallotView.js
- frontend/src/components/Election/Voting/VotePage.tsx
- frontend/src/index.css
I tried moving a bunch of the colors to variables
Long term these might end up in theme.js so this might be an incremental solution
> Clean up colors in CSS

- frontend/src/components/Election/Voting/GenericBallotView.js
- frontend/src/components/Election/Voting/StarBallotView.js
- frontend/src/components/Election/Voting/StarPRBallotView.js
- frontend/src/components/Election/Voting/VotePage.tsx
- frontend/src/index.css
Addresses #281 
- Reduces size of ballot title font and increases padding.
- Fixes issues with stars numbers shifting to the right on smaller screens and attempts to center them more. The centering is a little iffy, might need to reduce font size on smaller screens.
- Centers ballot circles/numbers a little better and aligns with stars. 
- Makes title/description/instructions/ballot spacing more even and makes instructions more responsive
Before
After
> Ballot updates

- frontend/src/App.tsx
- frontend/src/components/Footer.tsx
- frontend/src/components/Header.js
- frontend/src/components/LandingPage.tsx
Adds basic footer, recommendations for what else to put are welcome. 
Some potentials would be site navigation, GitHub contribution info, copyright info, feedback options.
Also changes STAR Voting Elections Hosting to STAR Elections, will likely change again later.
> Adding Footer

- frontend/src/components/Header.js
We decided to increase the nav font size to match the home screen, but I feel like it was taking up too much space when logged in, so I decreased the font size again
Before
After
> Decrease nav size

- frontend/src/components/Election/Results/DetailedResultsExpander.tsx
- frontend/src/components/Election/Results/Results.js
- frontend/src/components/Election/Results/ViewElectionResults.tsx
- frontend/src/components/ElectionForm/Races.tsx
- frontend/src/components/Sandbox.tsx
- frontend/src/components/util.js
This updates the race results page to put each race in a expandable area. This also adds scrolling logic to the election form when errors are made in the form
https://github.com/Equal-Vote/star-server/assets/9289903/0c89341c-64e7-4827-bde1-25b66ea1a937
Note: The bug at the end of the video is also fixed in this PR
> Expandable race results

- frontend/src/components/ElectionForm/AddCandidate.tsx
- frontend/src/components/ElectionForm/Races.tsx
- frontend/src/index.css
I made an improvement to the candidate photo positioning on the election form
https://github.com/Equal-Vote/star-server/assets/9289903/649a62a2-21a8-4842-ba3d-3a197ac5622e
> Candidate photo positioning

- docs/keycloak_configuration.md
- frontend/src/hooks/useAuthSession.ts
Tweak keycloak docs based on our latest adjustments
> Update keycloak documentation and bypass logout screen

- backend/sample.env
- backend/src/Controllers/sendInvitesController.ts
- backend/src/Routes/elections.routes.js
- backend/src/Services/Email/EmailTemplates.ts
- frontend/sample.env
- frontend/src/components/Election/Admin/EditElectionRoll.tsx
- frontend/src/components/Election/Admin/ViewElectionRolls.tsx
Adds route for sending individual invite 
Displays email invite status on individual voter page. If email failed will display debug info.
Adds button on individual voter page to send invite. This will send even if previous invite was successful. 
none
> Email updates

- frontend/src/components/Election/Voting/GenericBallotView.js
- frontend/src/components/Election/Voting/StarBallotView.js
- frontend/src/components/Footer.tsx
- frontend/src/index.css
From Sara's feedback, adjusts some font sizing and spacing on ballot and changes order of footer sections and about us wording.
Footer
Ballot images to come soon, dev DB is not starting
> Ballot update from feedback

- backend/src/Tabulators/Star.ts
- frontend/src/components/Election/Admin/ViewElectionRolls.tsx
- frontend/src/components/Election/Results/STARResultSummaryWidget.tsx
- frontend/src/components/Election/Sidebar.tsx
- frontend/src/components/Election/Voting/BallotPageSelector.js
- frontend/src/components/Election/Voting/VotePage.tsx
- frontend/src/components/ElectionForm/AddCandidate.tsx
- frontend/src/components/ElectionForm/AddElection.tsx
- frontend/src/components/ElectionForm/ElectionForm.tsx
- frontend/src/components/ElectionForm/Races.tsx
* Fix bug with how results are sorted (image shows bug, note the finalists don't match between the 2 rounds)
* Add no preference vote counts to the details
* Remove next button on ballot if there's no more pages (see original feedback https://www.youtube.com/watch?v=Py6hg2jxxy8&t=751s )
* Rename Home on admin page to Voting Page
* Add no voters page info when the voter roll is empty
* Add ability to remove candidates when creating election
https://github.com/Equal-Vote/star-server/assets/9289903/1846e13f-8c49-400c-98e1-8e21f997d259
* Minor wording tweaks on the election creation process
fixes #302
> UX improvements addressing feedback

- frontend/src/components/ElectionForm/ElectionForm.tsx
This breaks some of the longer prompts at the end of the election creation process into bullet points
> Election creation prompts

- backend/src/Services/Email/EmailTemplates.ts
- frontend/src/components/Election/ElectionHome.tsx
- frontend/src/components/Election/VoterAuth.tsx
This adds a message when the election is in draft mode and disables the voter id box if it's already been given
> Election home tweaks

- frontend/src/components/Election/VoterAuth.tsx
My previous PR broke the voter id login experience, this one should fix it
> Voter auth hot fix

- frontend/src/components/Election/Admin/AdminHome.tsx
- frontend/src/components/Election/Admin/EditElectionRoll.tsx
- frontend/src/components/Election/Admin/ViewElectionRolls.tsx
- frontend/src/components/Election/ElectionHome.tsx
- frontend/src/components/Election/ShareButton.tsx
- frontend/src/components/Election/Voting/Thanks.tsx
- frontend/src/hooks/useAPI.ts
Add more snacks to improve button feedback
> Add more snacks for button feedback

- frontend/src/components/Election/Admin/AdminHome.tsx
- frontend/src/components/Election/Admin/EditElectionRoll.tsx
- frontend/src/components/Election/Admin/ViewBallot.tsx
- frontend/src/components/Election/Admin/ViewBallots.tsx
- frontend/src/components/Election/ElectionHome.tsx
- frontend/src/components/Election/Voting/Thanks.tsx
- frontend/src/components/ElectionForm/ElectionDetails.tsx
- frontend/src/components/ElectionForm/SummaryPage.tsx
- frontend/src/components/Elections.tsx
- frontend/src/components/util.js
More date format into a shared function so it can be consistent
#fixes 326
> Make time consistent with timezone

- frontend/public/index.html
Add a feedback button from freshdesk
The specific fields can be modified within freshdesk
fixes #284
> Add freshdesk feedback button

- backend/src/Controllers/getElectionResultsController.ts
- backend/src/Controllers/sandboxController.ts
- backend/src/Tabulators/ITabulators.ts
- domain_model/Race.ts
- domain_model/Results.ts
- frontend/src/components/Election/Results/MatrixViewer.js
- frontend/src/components/Election/Results/Results.tsx
- frontend/src/components/Election/Results/ViewElectionResults.tsx
- frontend/src/components/Sandbox.tsx
- frontend/src/hooks/useAPI.ts
Adds types to results on frontend, changes results response format slightly to make it easier for typescript to distinguish the different race results types. No functional changes.
None, but will make it easier to update results pages in the future.
> Results types

- backend/src/Controllers/getElectionResultsController.ts
- backend/src/Controllers/sandboxController.ts
- backend/src/Tabulators/ITabulators.ts
- domain_model/Race.ts
- domain_model/Results.ts
- frontend/src/components/Election/Results/MatrixViewer.js
- frontend/src/components/Election/Results/Results.js
- frontend/src/components/Election/Results/ViewElectionResults.tsx
- frontend/src/components/Sandbox.tsx
- frontend/src/hooks/useAPI.ts
Reverts Equal-Vote/star-server#352
Failing docker build
> Revert "Results types"

- docs/index.md
> Volunteer list

- docs/index.md
Add more names to the volunteer list
> Add some more names

- frontend/src/components/Election/Election.tsx
- frontend/src/components/ElectionContextProvider.tsx
Part of the larger admin page work. Was getting messy passing election data and functions around between components so I made another context provider. Right now this only is used at the top level and some components I'm working on. Next will need to add the useContext hooks to the subcomponents.
None
None
> Adding election context provider

- package.json
Changed start scripts in #338, need to add build to heroku start up now
> adding build step to heroku script

- Dockerfile
NPM package missing from docker image for running start script
> Adding top level npm package to docker image for npm scripts

- frontend/src/components/Header.js
This hides the email when you're logged in and makes the experience the same for mobile and desktop
https://github.com/Equal-Vote/star-server/assets/9289903/419acb92-f7b0-4eee-a63a-9bff0ba3c6ba
fixes #331
> Rework login / logout button

- backend/src/Models/ElectionRolls.ts
- backend/src/Models/Elections.ts
- frontend/src/components/LandingPage.tsx
- frontend/src/components/LandingPage/FeaturedElection.tsx
- frontend/src/components/LandingPage/LandingPageHero.tsx
Add some feature flags and update the featured election buttons to query the election data
fixes #391
fixes #392
fixes #393
> Feature Flags & Query Featured Elections

- frontend/src/components/Header.js
Make Elections header button center clickable.
> Make Elections header button center clickable

- frontend/src/components/About.tsx
Created a first draft of the about page
(the overflowing mobile view will be fixed once we have a final name)
fixes #407
> Draft out about page

- frontend/public/index.html
> Add matomo tracking as a test

- frontend/src/components/Election/Admin/AddElectionRoll.tsx
Add dynamic placeholder text to make the input format more clear
https://github.com/Equal-Vote/star-server/assets/9289903/1e5d67a7-44b0-4fa9-a679-20c95eec5535
> Add dynamic placeholder text when entering voter data

- backend/src/Controllers/sandboxController.ts
- frontend/src/components/Sandbox.tsx
- frontend/src/hooks/useAPI.ts
Some updates to the sandbox to prevent errors that break the page.
Adds API hook for sandbox.
Adds useEffect to refetch data after inputs change.
Adds some input validation to check that the correct number of  votes are added per line and filters out spaces, empty strings, and NaNs. This could probably be done better with some regex but I need relearn some of that.
Sends back number of winners, voting method, and candidates with results, and only render results with data sent back. This prevents errors where user would change the number of winners or voting method that wouldn't work with the results currently loaded and crash the page.
Fixes #367, #325, #314, #132
> Sandbox updates

- Dockerfile
- frontend/src/components/Header.js
- frontend/src/theme.tsx
I added a theme for detecting your browser's default theme (and for me that means dark mode), and also set the environment variable for the featured elections
Also ran it as a docker image to verify the docker file update
fixes #432
> Detect dark mode and set featured elections

- Dockerfile
- backend/src/Controllers/addElectionRollController.ts
- backend/tsconfig.json
- frontend/build.js
- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Election/Admin/AddElectionRoll.tsx
- frontend/src/components/ElectionContextProvider.tsx
- frontend/src/components/ElectionForm/CreateElectionTemplates.tsx
- frontend/start.js
- frontend/tsconfig.json
- package-lock.json
- shared/SharedConfig.ts
Update create-react-app to let us use shared files
> Get voter limit from shared config

- frontend/public/index.html
- frontend/src/components/Election/Voting/ApprovalBallotView.js
- frontend/src/components/Election/Voting/GenericBallotView.js
- frontend/src/components/Election/Voting/PluralityBallotView.js
- frontend/src/components/Election/Voting/RankedBallotView.js
- frontend/src/components/Election/Voting/StarBallotView.js
- frontend/src/components/Election/Voting/StarPRBallotView.js
- frontend/src/components/Header.js
- frontend/src/index.css
* Add election type and read more link to the ballot
* Move feedback button to dropdown for mobile view (it was too easy to accidentally click the feedback button on mobile)
https://github.com/Equal-Vote/star-server/assets/9289903/37f73789-16c2-496c-8ead-ce88334a621a
fixes #439 #443 #444
> Add voting method info to ballot, and move featured button to hamburger for mobile

- package.json
Moved migration script, didn't fix the top level script start script that calls it.
> Fixing bug in start up script

- frontend/src/components/Election/ElectionHome.tsx
Ends at was showing the wrong time
> Fix end time

- docs/contributions/Infrastructure/2_devops_local_setup.md
Here's documentation for getting onboarded as a DevOps engineer
> Add devops documentation

- frontend/src/components/Election/ElectionHome.tsx
Hotfixing a bug where the wrong date is displayed post-election
> Hotfix how end time is displayed post election

- backend/src/Controllers/auth.controllers.ts
- frontend/src/components/Header.js
> Remove "My invitations" - https://github.com/Equal-Vote/star-server/issues/490

- frontend/src/components/Election/Voting/Thanks.tsx
- frontend/src/components/Footer.tsx
> Fix Donations link 

- packages/frontend/src/components/About.tsx
- packages/frontend/src/components/Footer.tsx
Removed unwanted information from about us section in the footer, and updated the donation link in the footer to follow https://www.equal.vote/donate. Closes #523 
> fixes #523
> fix: updated the information on the about us section and fixed donation links

- package-lock.json
- packages/backend/src/Tabulators/AllocatedScore.ts
- packages/backend/src/Tabulators/Star.ts
- packages/frontend/src/components/Election/Election.tsx
- packages/frontend/src/components/Election/ElectionHome.tsx
- packages/frontend/src/components/Election/Results/Results.tsx
- packages/frontend/src/components/Election/Results/STAR/STARDetailedResults.tsx
- packages/frontend/src/components/Election/Results/STAR/STARResultDetailedStepsWidget.tsx
- packages/frontend/src/components/Election/Results/STAR/STARResultSummaryWidget.tsx
- packages/frontend/src/components/Election/Results/STAR/STARResultTableWidget.tsx
- packages/frontend/src/components/Election/Results/ViewElectionResults.tsx
- packages/frontend/src/components/util.jsx
- packages/frontend/src/index.css
- packages/shared/package.json
- packages/shared/src/domain_model/ITabulators.ts
- Replace "No Preference" with "Equal Preference" every in the front end
- Count Equal Preference distribution support in the tabulator
- Add view results button when opening the ballot
- Add landscape support
- Setup shared Widget / WidgetContainer system
- Add landscape support
- Adjust subcomponents layout on results
- Set limit on how many candidates are shown in top level results
> Be sure to include both desktop and mobile views (mobile could be as low as 320 px wide)
> Make results prettier

- .github/workflows/node.js.yml
- Dockerfile
chore: downgrade Node version to latest LTS release (20.x)
> chore: downgrade Node version to latest LTS release (20.x)

- .github/workflows/build-push-deploy.yml
- Dockerfile
- docs/contributions/1_local_setup.md
- package-lock.json
- package.json
- packages/backend/package.json
- packages/frontend/README.md
- packages/frontend/package.json
- packages/shared/package.json
feat: add clean scripts and update docs accordingly
> feat: add clean scripts and update docs accordingly

- packages/frontend/vite.config.ts
Update optimizeDeps in vite config
This was causing import issues
> Fix shared path in vite config

- packages/backend/src/Models/Elections.ts
- packages/frontend/src/components/Header.tsx
> feat: publlic elections tab implemented

- .dockerignore
- Dockerfile
- package.json
- replace.sh
> Setting up React to use env vars on launch, and optimizing docker build

- .github/workflows/build-push-deploy.yml
> Adding deploy step for argocd repo to GitHub Action

- packages/frontend/src/components/About.tsx
- packages/frontend/src/components/Election/Voting/VotePage.tsx
- changes 'submit vote' button on Vote page from 'outline' to 'contained' for additional contrast
- added myself as a contributor to the About page
- n/a
- fixes #543
> Update vote page 'submit vote' button

- packages/frontend/src/components/About.tsx
- packages/frontend/src/components/util.jsx
Fixes #577 
Made the change to remove the gray color from the scoring results
> fix: removal of the gray color in the scoring results

- docs/help/1_faq.md
Adds FAQ page template, entries can be updated easily within github.
closes #595
> Adding FAQ template

- docs/help/1_faq.md
- packages/frontend/src/components/LandingPage/LandingPageHero.tsx
- packages/frontend/src/components/LandingPage/LandingPageStats.tsx
When logged in, change last page of carrousel to have button to open full editor instead of log in button.
Update stats boxes to switch to column flex direction on small screens. 
closes #585 
closes #576
> Home page fixes

- packages/frontend/src/i18n/en.yaml
> Added link to Equal Preference FAQ article to copy in final Tabulation Step

- package-lock.json
- packages/backend/package.json
- packages/backend/src/Controllers/castVoteController.ts
- packages/backend/src/Controllers/getElectionsController.ts
- packages/backend/src/Routes/elections.routes.js
- packages/backend/src/app.ts
- packages/backend/src/index.ts
- packages/backend/src/socketHandler.ts
- packages/frontend/package.json
- packages/frontend/sample.env
- packages/frontend/src/components/Election/Voting/VotePage.tsx
- packages/frontend/src/components/LandingPage.tsx
- packages/frontend/src/components/LandingPage/LandingPageStats.tsx
- packages/shared/package.json
> Dynamically update front page stats based on socket.io

- packages/frontend/src/i18n/en.yaml
> added csamuele as contributer

- packages/frontend/src/components/ElectionForm/Races/useEditRace.tsx
- packages/frontend/src/i18n/en.yaml
> Forced race title to be unique and fixed bug where races were not being validated for the first two

- packages/backend/src/Services/Email/EmailTemplates.ts
Created a new email template within mailchimp
I couldn't think of a lot of context to add, so the image is the biggest change
Also added an environment variable for the from email
fixes #584 #644 
**new**
**old**
> Polish email

- Dockerfile
- packages/backend/src/Models/Elections.ts
- packages/backend/src/Util.ts
- packages/backend/src/app.ts
- packages/backend/tsconfig.json
- packages/frontend/index.html
- packages/frontend/src/components/Election/ElectionHome.tsx
- packages/frontend/src/components/Election/Voting/Thanks.tsx
- packages/frontend/src/components/Sandbox.tsx
- The backend will dynamically insert meta tags
- If the url contains an election id then the meta tag content will correspond to that election
- The preview image is dynamically generated using imagekit
[Base Image In ImageKit](https://ik.imagekit.io/equalvote/media_preview.png)
Here's an example of the preview image in slack
[Exactly 5 candidates](https://ik.imagekit.io/equalvote/tr:l-text,i-US%202024%20Presidential%20Election%20,w-900,lx-50,ly-180,fs-45,ff-Montserrat-Black.ttf,l-end:l-image,i-ik_canvas,bg-FFFFFF,lfo-bottom_left,w-1000,h-12,l-end:l-text,i-Kamala%20Harris%20(D),w-400,lx-30,ly-470,fs-30,ia-left,ff-Montserrat-Black.ttf,l-end:l-text,i-Donald%20J.%20Trump%20(R),w-400,lx-30,ly-580,fs-30,ia-left,ff-Montserrat-Black.ttf,l-end:l-text,i-Robert%20F.%20Kennedy%20Jr.%20(I),w-400,lx-3 …
> Add social media preview for star voting elections

- packages/frontend/src/components/ElectionForm/Details/ElectionAuthForm.tsx
- packages/frontend/src/components/ElectionForm/Details/ElectionDetailsDialog.tsx
- packages/frontend/src/components/ElectionForm/Details/ElectionDetailsForm.tsx
- packages/frontend/src/components/ElectionForm/Details/ElectionDetailsInlineForm.tsx
- packages/frontend/src/components/ElectionForm/Details/ElectionStateChip.tsx
- packages/frontend/src/components/ElectionForm/SummaryPage.tsx
- packages/frontend/src/theme.tsx
Got rid of the key:value pattern for the Election details form and replaced it with typography meant to signal it instead for a cleaner look. Added a chip to display election state. 
fixes issue #546
> Updated the look of the Election details form

- .vscode/launch.json
- .vscode/tasks.json
- packages/frontend/src/components/Election/Admin/ViewBallots.tsx
- packages/frontend/src/components/Election/Admin/ViewElectionRolls.tsx
- packages/frontend/src/components/Election/Voting/RankedBallotView.jsx
fixed bug where hitting back didn't take you to the right table when viewing ballot or voter. 
https://github.com/user-attachments/assets/1999162e-f1ce-47df-a870-1f57fd8acd72
> fixes #474
> Hitting back when you have a ballot or voter selected takes you back to the corresponding table

- packages/frontend/src/components/Election/Voting/GenericBallotView/GenericBallotView.tsx
- packages/frontend/src/i18n/en.yaml
Just added the extra bit have the instructions include how many winners will be in the race.
> added pluralization for multiwinner races

- package-lock.json
- packages/frontend/package.json
- packages/frontend/src/components/DragAndDrop/SortableItem.css
- packages/frontend/src/components/DragAndDrop/SortableItem.tsx
- packages/frontend/src/components/DragAndDrop/SortableList.css
- packages/frontend/src/components/DragAndDrop/SortableList.tsx
- packages/frontend/src/components/DragAndDrop/SortableOverlay.tsx
- packages/frontend/src/components/DragAndDrop/index.ts
- packages/frontend/src/components/Election/Voting/RankedBallotView.tsx
- packages/frontend/src/components/ElectionForm/Candidates/AddCandidate.tsx
- packages/frontend/src/components/ElectionForm/Races/RaceForm.tsx
Updated added candidate UX to make it scroll when the new element is focused instead of when it is added. 
I updated the delete behavior to make it so a candidate is deleted when they are cleared wherever it is in the list, unless there is only one left (not including the grayed out one). I made it so you have to press spacebar again on the cleared candidate before it is deleted though, because it can be frustrating if it happens automatically while you are trying to edit a candidate. 
I also replaced the up and down arrows with a drag and drop list. 
For some reason my screen recorder isn't working. 
closes #665
> 665 add candidate UX

- .vscode/tasks.json
- packages/frontend/src/components/ElectionForm/Details/ElectionStateChip.tsx
- packages/frontend/src/components/EnhancedTable.tsx
updated the election state column to use the colored chips in the elections table
closes #664
> 664 election state chip for election table

- packages/frontend/src/components/Election/Results/STAR/STARExtraContext.tsx
- packages/frontend/src/components/Election/Results/STAR/STARResultSummaryWidget.tsx
- packages/frontend/src/i18n/en.yaml
Adds context when the top scoring candidate loses in the runoff. 
closes #561
> 561 runoff context

- packages/backend/src/OpenApi/swagger.json
- packages/backend/src/OpenApi/swaggerSpec.ts
- packages/backend/src/app.ts
> updated authentication instructions in swagger doc

- packages/backend/src/Controllers/Ballot/getAnonymizedBallotsByElectionIDController.ts
- packages/backend/src/app.ts
- packages/frontend/src/components/Election/Admin/ViewBallots.tsx
- packages/frontend/src/components/Election/Results/BallotDataExport.tsx
- packages/frontend/src/components/Election/Results/ViewElectionResults.tsx
- packages/frontend/src/components/MenuButton.tsx
- packages/shared/src/domain_model/Ballot.ts
> added json download option for ballot data

- packages/backend/src/Routes/elections.routes.ts
- packages/shared/src/domain_model/Ballot.ts
fixed errors with posting ballots where it was invalidating proper ballots.
> fix ballot validation

- packages/frontend/src/index.css
> made hyperlinks green

- packages/frontend/src/components/ElectionForm/ElectionSettings.tsx
- packages/shared/src/domain_model/ElectionSettings.ts
max rankings was being sent as a string rather than a number, I fixed the frontend to send it as a number
closes #690
> fixed frontend to comply with max rankings validation

- packages/frontend/index.html
- packages/frontend/src/theme.tsx
Updated typography to use a Sans Serif font.
Modified theme so that buttons could use lower case.
OLD:
NEW:
OLD:
NEW
> Change to Nunito Sans

- packages/frontend/src/components/LandingPage/LandingPagePricing.tsx
> Restore maxwidth to pricing options

- packages/frontend/src/components/LandingPage/LandingPageFeaturedElections.tsx
- packages/frontend/src/components/LandingPage/LandingPageFeatures.tsx
- packages/frontend/src/components/LandingPage/LandingPagePricing.tsx
- packages/frontend/src/components/LandingPage/LandingPageSignUpBar.tsx
- packages/frontend/src/components/util.tsx
The effect is bad for usability and also reset if you scroll up and down.
https://share.cleanshot.com/zLLKPRp9
Ignore width issues, unrelated to this PR.
> Remove fade-in effect from landing pages.

- packages/frontend/src/components/ElectionForm/Races/useEditRace.tsx
> Be sure to include both desktop and mobile views (mobile could be as low as 320 px wide)
> Clear race dialogue on saving

- packages/backend/src/Controllers/Ballot/castVoteController.ts
- packages/backend/src/Controllers/Election/getElectionResultsController.ts
- packages/backend/src/OpenApi/swagger.json
- packages/backend/src/Tabulators/IRV.test.ts
- packages/backend/src/Tabulators/IRV.ts
- packages/backend/src/Tabulators/STV.test.ts
- packages/backend/src/test/editElection.test.ts
- packages/frontend/src/components/AnonymizedBallotsContextProvider.tsx
- packages/frontend/src/components/Election/Results/BallotDataExport.tsx
- packages/frontend/src/components/Election/Results/Results.tsx
- packages/frontend/src/components/Election/Results/components/RectPieChart.tsx
- packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx
- packages/frontend/src/components/Election/Results/components/VoterErrorStatsWidget.tsx
- packages/frontend/src/components/ElectionSettingInference.ts
- packages/frontend/src/components/UploadElections.tsx
- packages/frontend/src/components/cvrParsers.tsx
- packages/frontend/src/components/public_archive_settings.yaml
- packages/frontend/src/components/util.tsx
- packages/shared/src/domain_model/ElectionSettings.ts
- packages/shared/src/domain_model/ITabulators.ts
- packages/shared/src/domain_model/Vote.ts
This PR adds support for tracking overvote and duplicate rank errors.
> Add voided ballot tracking when uploading prior elections

- packages/frontend/src/i18n/pl.yaml
> Update pl.yaml - 32 lines

- package-lock.json
`npm audit fix` made some changes but did not claim to have resolved all warnings. It said that for some packages, no fixes were available yet.
> Result of npm audit.

- packages/frontend/src/components/Election/Admin/ViewBallot.tsx
Removed the submitted date
> Fix for Issue https://github.com/Equal-Vote/star-server/issues/811
> fix: removed submitted date

- packages/frontend/src/i18n/en.yaml
> Fix typo "Proportaionl"

- package-lock.json
Result of another `npm audit fix`.
> Result of another `npm audit fix`.

- package-lock.json
Result of running `npm audit fix` at about Sun Mar 23 06:01:19 PM UTC 2025
> Yet another result of running `npm audit fix`.

- docker-compose.yml
- realm.json
- testing/.github/workflows/playwright.yml
- testing/.gitignore
- testing/package-lock.json
- testing/package.json
- testing/playwright.config.ts
- testing/tests-examples/demo-todo-app.spec.ts
- testing/tests/example.spec.ts
> Automatically import Dev realm when creating keycloak container

- docker-compose.yml
- docs/contributions/developers/1_local_setup.md
> fixed environment variables for web service in docker compose and removed keycloak configuration step

- testing/tests/example.spec.ts
> testing a failed test with github pages

- .github/workflows/end-to-end-tests.yml
> don't name the artifact for the playwright report

- .github/workflows/end-to-end-tests.yml
- testing/tests/example.spec.ts
> remove deploying to pages for now

- packages/frontend/src/App.tsx
- packages/frontend/src/components/About.tsx
- packages/frontend/src/components/DragAndDrop/SortableItem.tsx
- packages/frontend/src/components/Election/Admin/EditRoles.tsx
- packages/frontend/src/components/Election/Admin/SendEmailDialog.tsx
- packages/frontend/src/components/Election/VoterAuth.tsx
- packages/frontend/src/components/Election/Voting/GenericBallotView/BubbleGrid.tsx
- packages/frontend/src/components/Election/Voting/GenericBallotView/GenericBallotGrid.tsx
- packages/frontend/src/components/Election/Voting/GenericBallotView/ScoreIcon.tsx
- packages/frontend/src/components/Election/Voting/VotePage.tsx
- packages/frontend/src/components/ElectionForm/Candidates/AddCandidate.tsx
- packages/frontend/src/components/ElectionForm/CreateElectionDialog.tsx
- packages/frontend/src/components/ElectionForm/Details/ElectionDetailsForm.tsx
- packages/frontend/src/components/ElectionForm/Details/ElectionDetailsInlineForm.tsx
- packages/frontend/src/components/ElectionForm/ElectionSettings.tsx
- packages/frontend/src/components/ElectionForm/Races/Race.tsx
- packages/frontend/src/components/ElectionForm/Races/RaceForm.tsx
- packages/frontend/src/components/Footer.tsx
- packages/frontend/src/components/Header.tsx
- packages/frontend/src/components/util.tsx
- packages/frontend/src/i18n/en.yaml
- testing/playwright.config.ts
- testing/tests/create-election.spec.ts
- testing/tests/election-with-rolls.spec.ts
- testing/tests/election-without-rolls.spec.ts
- testing/tests/full-runthrough.spec.ts
I updated unlabeled components to use aria label and used more descriptive labels. I'm not sure why so many components have the name attribute, it seemed a bit redundant, but I tried to change just the ones I've been working on
> End to end testing

- docker-compose.yml
- docs/contributions/1_developers.md
- docs/contributions/developers/1_local_setup.md
- docs/contributions/developers/3_troubleshooting.md
Replace star-server with bettervoting in the contribution guide to match the name change
> fix: replace star-server with bettervoting in docs

- packages/frontend/src/components/ElectionForm/Races/RaceForm.tsx
- packages/frontend/src/components/EnhancedTable.tsx
I changed the heading as per required in the in the issue
> fixes issue #814
> fix:consistency rank and election #814

- packages/frontend/src/components/Election/ShareButton.tsx
Prefill the posts with reasonable information when sharing an election or poll to X and reddit.
fixes #908
> feat: supply titles when sharing to X and reddit

- packages/frontend/src/i18n/en.yaml
Changed bettervoting.com to BetterVoting.com
> Changed bettervoting.com to BetterVoting.com

- .gitignore
> Ignoring personal pre-commit files.
