Equal-Vote/bettervoting

.gitignore
frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/components/AddElection.js
frontend/src/components/VotePage.js

I was trying to learn about react, and things weren't working for me because I was using react-router-dom v6 and most tutorials are still using v5
I followed this video, https://www.youtube.com/watch?v=k2Zk5cbiZhg , to figure out the v6 changes, and applied them to the frontend

Update react-router-dom to v6

---

backend/sample.env
backend/src/app.ts
frontend/src/App.tsx

This update will let us use the Keycloak Dev Realm for local testing. This way we can add a bunch of test users without polluting the production user base
In addition to the code change, I also did the following in KeyCloak
* Create a new Realm called "STAR Voting Dev"
* Create a new client within the realm called star_vote_web
* Copied all the settings from the production realm's star_vote_web client to the dev realm client
Here's the remaining manual steps on the heroku end
* Update the PR deployment .env to use the dev keycloak url + secret
* Update the Production .env to use the prod keycloak url (the prod secret is still the same)

Add support for Keycloak Dev Realm

---

backend/src/ServiceLocator.ts
backend/src/__mocks__/ServiceLocator.ts
backend/src/test/createElection.test.ts
backend/src/test/editElection.test.ts
backend/src/test/emailRoll.test.ts
backend/src/test/idRoll.test.ts
backend/src/test/register.test.ts

This sets up a Mock for the Service Locator, rather than mocking each databases individually.  This will be required for updating the mock-databases to handle atomic transactions across multiple tables.

sets up the Mock ServiceLocator

---

backend/src/Controllers/ballots.controllers.ts
backend/src/Controllers/controllerUtils.ts
backend/src/Models/Ballots.ts
backend/src/Models/Elections.ts
backend/src/Models/__mocks__/Ballots.ts
backend/src/Models/__mocks__/Elections.ts
backend/src/test/TestHelper.ts
backend/src/test/editElection.test.ts
backend/src/test/emailRoll.test.ts
backend/src/test/idRoll.test.ts
backend/src/test/testInputs.ts
domain_model/Ballot.ts
domain_model/Election.ts

Updates ballot_id and election_id to be uuids (universally unique ids).  This means they can be generate by different processes without coordination.
THIS WILL BREAK production data, and should be accompanied by a wipe of the prod database.  (theoretically we could run a migration, but since we don't have any needed data yet, just nuke it)

changing ballot_id and election_id to be Uids

---

backend/src/ServiceLocator.ts
backend/src/Services/EventQueue/PGBossEventQueue.ts

Configuring options for PG-Boss to poll more often
Also fixing the Postgres connection options to use the same config set in the SeviceLocator

configuring options for pg boss to process events faster

---

backend/src/Services/EventQueue/PGBossEventQueue.ts

Minor change to use teamSize instead of batchSize. This will still run 5 jobs in a polling period but uses one job per handler instead of passing an array of jobs to the handler.

Event queue batch size switched to team size

---

backend/src/Controllers/editElectionController.ts
backend/src/Controllers/editElectionRolesController.ts
backend/src/Controllers/elections.controllers.ts
backend/src/Routes/elections.routes.js
domain_model/permissions.ts
frontend/package-lock.json
frontend/src/components/Election/Admin/Admin.tsx
frontend/src/components/Election/Admin/EditElectionRoll.tsx
frontend/src/components/Election/Admin/EditRoles.tsx
frontend/src/components/Election/Admin/ViewElectionRolls.tsx
frontend/src/components/Election/Election.tsx
frontend/src/components/Election/ElectionHome.tsx
frontend/src/components/Election/ShareButton.tsx
frontend/src/components/Election/Sidebar.tsx
frontend/src/components/Election/Voting/Thanks.tsx
frontend/src/components/Election/Voting/VotePage.tsx
frontend/src/components/PermissionHandler.tsx

Along with voter_auth data the backend will now send user permissions. Created a component "PermissionHandler" that only renders a component if user has required permissions and moved some of our components into permissions handlers. 
Created an edit roles page so election owner can add credentialers, admins, and auditors. 
Added a simple "thanks for voting page" instead of routing back to home page. This page will have links to share and link to results page. Page could use some more styling in the future and maybe a "learn more about star voting" or "donate to equal vote" links.

Permission Handling, thanks for voting page, edit roles page

---

backend/src/Tabulators/ITabulators.ts
backend/src/Tabulators/Star.test.ts
backend/src/Tabulators/Star.ts

We have updated our score tiebreaker protocol again, flowchart [here](https://docs.google.com/drawings/d/1L-tIDY6-8OeKGzW0w1eh2EUjlHbarEcsfvhsegMT8qg/edit?usp=sharing).
Before we would look for any weak Condorcet winner, if none existed we'd look for a candidate with the most five star votes, if none existed we'd pick a random winner.
Now we eliminate candidates with the most head to head losses until one can advance. If that doesn't work we look for a candidate with the most five star votes. If that doesn't work we eliminate candidates with the least five star votes. Finally if that doesn't work we pick a random winner. 
While more complex this should let us select better winners, cover most weird edge cases, and avoid random winners more often.

New score tiebreaker protocol

---

docs/keycloak_deployment.md

I've renewed the certificate and also setup auto-renewal so that we won't need to do this anymore
I updated the documentation since I added a post-hook that was specific to our setup

Add instructions for certificate auto-renewal

---

backend/src/Controllers/getElectionResultsController.ts
backend/src/Tabulators/Approval.ts
backend/src/Tabulators/Plurality.ts
backend/src/Tabulators/RankedRobin.ts
frontend/src/components/Election/Voting/BallotSelector.js
frontend/src/components/Election/Voting/RankedBallotView.js
frontend/src/components/ElectionForm/Races.tsx

Plurality and Approval are still buggy regarding ties. This randomizes the order of tied candidates and grabs the first tied candidate if random tiebreakers are enabled. Won't work if random tiebreakers are not enabled so it will need to be refactored some time in the future, but this temp fix will work in the meantime.
Changed Ranked Robin validity check to count 0 as valid. It already checks for 0 ranks later in the code and considers them as last place ranks.
Also changed Ranked-Robin to RankedRobin in the frontend. The '-' doesn't work with the VotingMethodSelector in the backend.

More plurality and approval bug fixes, Ranked Robin name fix

---

backend/src/Tabulators/Star.ts

Currently logs objects: "Cat defeats Dog in runoff tiebreaker with a score of [object Object] to [object Object]"

Log scores correctly in runoff tiebreaker

---

.vscode/launch.json

Allows you to add breakpoints in express app and debug code easier in vscode. Removes old code used for python app.
Click the "Debug Server" button to launch server and break on breakpoints and uncaught exceptions.

Running express app in debug mode in vscode

---

frontend/src/components/Election/Results/MatrixViewer.js
frontend/src/components/Election/Results/Results.js
frontend/src/components/ElectionForm/Races.tsx

Uses radio buttons for selecting voting method
https://files.slack.com/files-pri/T9TFU145P-F04VB54EJQY/image.png
Fixes issue with the edges of the results page getting cropped on mobile. I switched to using the MUI table component and set a max table width based on screen size. So now if the table is too big it creates a scrollable table that fits on the screen.
Original view:
Fixed view:

Voting method radio button and results page crop fix

---

frontend/sample.env
frontend/src/hooks/useAuthSession.js

Figured out that you can use env variables in react apps that get embedded at build time. Figured the keycloak url would be a good use for that.
Variables have to start with "REACT_APP_" which is why I can't use the existing KEYCLOAK_URL variable used in the backend.
Worked locally, creating PR to test in heroku.

Moving frontend keycloak url to env variable 

---

backend/src/Tabulators/Approval.test.ts
backend/src/Tabulators/Approval.ts
backend/src/Tabulators/IRV.test.ts
backend/src/Tabulators/IRV.ts
backend/src/Tabulators/ParseData.ts
backend/src/Tabulators/Plurality.test.ts
backend/src/Tabulators/Plurality.ts
backend/src/Tabulators/RankedRobin.test.ts
backend/src/Tabulators/RankedRobin.ts
backend/src/Tabulators/Star.test.ts
backend/src/Tabulators/Star.ts

Adding basic tests for approval, plurality, ranked robin, and IRV. 
There's probably some edge cases I missed but this adds the framework to add more later.

Tabulator tests

---

backend/package-lock.json
backend/package.json

Moving tests to dev dependencies, trying to reduce size of node modules in production
Also we don't use the star_tabulators package anymore. Maybe in the future we can move our current tabulators back to the star core repo and rerelease the updated npm package.

Moving tests to dev dependencies

---

frontend/src/components/Election/Results/DetailedResultsExpander.tsx
frontend/src/components/Election/Results/STARResultSummaryWidget.tsx
frontend/src/components/Election/Results/STARResultTableWidget.tsx
frontend/src/index.css

looks like sorting fixed it
I also added some automatic scrolling logic, and removed some excess padding from the results (it was bothering me that I had to scroll to see the full results on small elections)
https://github.com/Equal-Vote/star-server/assets/9289903/38aff004-406f-42da-a4b7-06de8ab02f1b
fixes #291

Fix bugs with yaxis cutoff and sorting candidates

---

frontend/src/components/Election/Admin/ViewElectionRolls.tsx
frontend/src/components/Elections.tsx
frontend/src/components/EnhancedTable.tsx

Adds enhanced tables built largely off of [the MUI example](https://mui.com/material-ui/react-table/#sorting-amp-selecting) but makes it a generalized component. 
This adds the ability to sort the table data, filter it either by a search term or by predefined groups, and adds pagination. 
Desktop/Mobile Before 
https://github.com/Equal-Vote/star-server/assets/41272412/613f66da-2d01-4c56-8aa8-6c21ece973d0
Desktop After
https://github.com/Equal-Vote/star-server/assets/41272412/eb898f1f-c1c2-4e34-81e7-bec0c1a960fd
Mobile After
The example also had a switch for denser padding, curious which one looks better, will pick one before merging.
https://github.com/Equal-Vote/star-server/assets/41272412/2bdd0a35-7de4-459e-90db-d2a8303d1dc5
none

Enhanced Tables

---

backend/src/Controllers/changeElectionRollController.ts
backend/src/Controllers/getElectionRollController.ts
frontend/src/components/Election/Admin/AddElectionRoll.tsx
frontend/src/components/Election/Admin/AdminHome.tsx
frontend/src/components/Election/Admin/EditElectionRoll.tsx
frontend/src/components/Election/Admin/EditRoles.tsx
frontend/src/components/Election/Admin/ViewBallot.tsx
frontend/src/components/Election/Admin/ViewBallots.tsx
frontend/src/components/Election/Admin/ViewElectionRolls.tsx
frontend/src/components/Election/Election.tsx
frontend/src/components/Election/Results/ViewElectionResults.tsx
frontend/src/components/Election/Voting/VotePage.tsx
frontend/src/components/ElectionForm/AddElection.tsx
frontend/src/components/ElectionForm/DuplicateElection.tsx
frontend/src/components/ElectionForm/EditElection.tsx
frontend/src/components/ElectionForm/QuickPoll.tsx
frontend/src/components/Elections.tsx
frontend/src/hooks/useAPI.ts
frontend/src/hooks/useFetch.ts

In order to make the front end more type safe this makes the useFetch hook type generic and allows us to specify the expected request body and response types. This PR also moves all api requests to our server to a new file useAPI.ts and defines all the expected types (the election results being the exception and is just type any for now).
This will allow us to have our API defined in one place, minimize redundant code, and clean up our components that use the API hooks.
Hopefully in the future this will also help us write some dedicated tests for these as well.

Make useFetch types generic, move API  hooks to one file

---

frontend/src/components/Elections.tsx

After logging in from the my elections page, the fetch request will be made before the login logic is finished, so the "election I manage" table will be empty and requires a page refresh. This makes the authSession.isLoggedIn() output a depenency to the fetch elections useEffect hook, so if the login status chages it will make the request again. Two requests are still made, but that shouldn't be an issue.
#330

refetch elections on login

---

frontend/src/components/Election/Admin/Admin.tsx
frontend/src/components/Election/Admin/EditRoles.tsx
frontend/src/hooks/useAPI.ts

Improves the edit election roles page
- Adds snack pop up on success
- No longer redirect on success
- Fetch latest election on success
- Adds padding to form and styled submit button
- Multiline placeholder emails to make it clear you can enter multiple emails. I'm iffy on this change, looking for feedback.
Mobile view with success snack
Addresses some issues raised in #330

Editing election roles page improvements

---

docs/index.md
frontend/src/App.tsx
frontend/src/components/About.tsx
frontend/src/components/Header.js

I updated the About button such that instead of going to the Star.org website, it goes to an About page. I added some placeholder text (figure out what should go here)

About goes to About page now instead of Starvoting.org

---

frontend/src/App.tsx
frontend/src/components/ConfirmationDialogProvider.tsx
frontend/src/components/Election/Admin/AdminHome.tsx

Made this as part of a larger task. Creates a context provider and hook for accessing confirmation dialog. The current dialog is just the MUI dialog, we can update the styling using #344. Basically, it adds a single dialog component at the top level of the app and uses a context provider to allow other components to open it, update the title and message, and get the response.
Built based on this tutorial https://akashhamirwasia.com/blog/building-expressive-confirm-dialog-api-in-react/ 
Uses some useRef and useCallback optimizations that are explained in there.

Adding confirmation dialog provider

---

frontend/src/components/Election/Results/Results.js

How the approval and plurality scores were displayed was incorrect. The scores array is sorted by score while and candidates array is in its original order. Since the scores array includes the candidate indexes, this gets the index of the candidate and retrieves the candidate name from the candidate array.
Before: 
After:
none

Fix scores order

---

backend/package-lock.json
backend/package.json
backend/src/Controllers/getElectionResultsController.ts
backend/src/Tabulators/AllocatedScore.test.ts
backend/src/Tabulators/AllocatedScore.ts
backend/src/Tabulators/Approval.test.ts
backend/src/Tabulators/Approval.ts
backend/src/Tabulators/IRV.ts
backend/src/Tabulators/ITabulators.ts
backend/src/Tabulators/Plurality.test.ts
backend/src/Tabulators/Plurality.ts
backend/src/Tabulators/RankedRobin.test.ts
backend/src/Tabulators/RankedRobin.ts
backend/src/Tabulators/Star.test.ts
backend/src/Tabulators/Star.ts

Previously random tiebreakers used a random number generator inside the tabulators to determine results. This issue with this is results would change every time you calculated them.
This adds a tiebreaker order list input to the tabulators so the outcome is determinative. The list uses strings so UUIDs can be used. To break a tie, the candidate with the lower string value wins. For example, 'A' defeats 'B', '0' defeats '1'. If no list is defined it defaults to using candidate index.
Now that candidate IDs are UUIDs, they can be used for their tiebreaker order so that random ties can be random but still determinative.

Adding tiebreaker order

---

backend/src/Models/ElectionRolls.ts
frontend/src/components/Election/Voting/VotePage.tsx

Three updates
- Comments out the info pages on the ballot for now
- Fixes bug for unshuffling candidates that immerged when we added candidate UUIDs
- Fixed bug when fetching roll for elections that just use email or IP. Wasn't checking for election ID so would find one with used email or IP and mark it as already voted.

Remove ballot info pages, misc bug fixes

---

domain_model/ElectionSettings.ts
frontend/src/components/Election/Election.tsx
frontend/src/components/Election/Voting/VotePage.tsx
frontend/src/components/ElectionForm/CreateElectionTemplates.tsx
frontend/src/components/ElectionForm/ElectionSettings.tsx
frontend/src/components/ElectionForm/QuickPoll.tsx

Adds setting to randomize candidate orders on the ballots. Order was already randomized but this allows you to disable it. Randomizing order is enabled by default. 
Also adds setting for requiring voter confirm they've read ballot instructions. Hooks are in to enable/disable it, but keeping it locked in the settings form for now until we get the checkbox added to the ballot.
Settings page
With randomization disabled
With randomization enabled
closes #335 
provides hook for #363

Random candidate order and voter instruction confirmations

---

frontend/src/components/Election/Admin/AddElectionRoll.tsx
frontend/src/components/Election/Admin/Admin.tsx
frontend/src/components/Election/Admin/EditElectionRoll.tsx
frontend/src/components/Election/Admin/ViewElectionRolls.tsx

Hides the "add voters" button when voter access is not open.
Hides the send invites button when email invites not enabled.
Hides email invite status when email invite not enabled.
Sets default values for add voter check boxes based on election. Should probably remove checkboxes in the future and just tell user what data is expected.
With email invites enabled
With email invites disabled
closes #310

Disable email buttons when not supported 

---

backend/src/Controllers/getElectionsController.ts
frontend/src/components/Election/Voting/ApprovalBallotView.js
frontend/src/components/Election/Voting/BallotPageSelector.js
frontend/src/components/Election/Voting/GenericBallotView.js
frontend/src/components/Election/Voting/PluralityBallotView.js
frontend/src/components/Election/Voting/RankedBallotView.js
frontend/src/components/Election/Voting/StarBallotView.js
frontend/src/components/Election/Voting/StarPRBallotView.js
frontend/src/components/Election/Voting/VotePage.tsx
frontend/src/components/ElectionForm/CreateElectionTemplates.tsx
frontend/src/components/ElectionForm/ElectionSettings.tsx
frontend/src/components/ElectionForm/QuickPoll.tsx
frontend/src/index.css

* Added checkbox to ballot
* Blur instructions when box isn't checked
* Changed bubbles to ovals
* Created a BallotContext
https://github.com/Equal-Vote/star-server/assets/9289903/97398af9-67cf-423f-a669-6542878675bc
fixes #405

Add checkbox to ballot for reading instructions

---

frontend/src/components/Election/Admin/AdminHome.tsx
frontend/src/components/Election/Admin/EditElectionRoll.tsx
frontend/src/components/Election/Admin/EditRoles.tsx
frontend/src/components/Election/Admin/ViewElectionRolls.tsx
frontend/src/components/Election/Voting/VotePage.tsx
frontend/src/components/ElectionCard.tsx
frontend/src/components/ElectionContextProvider.tsx
frontend/src/components/ElectionForm/AddElection.tsx
frontend/src/components/ElectionForm/Candidates/AddCandidate.tsx
frontend/src/components/ElectionForm/CreateElectionTemplates.tsx
frontend/src/components/ElectionForm/Details/ElectionDetails.tsx
frontend/src/components/ElectionForm/ElectionForm.tsx
frontend/src/components/ElectionForm/QuickPoll.tsx
frontend/src/components/ElectionForm/Races/RaceForm.tsx
frontend/src/components/ElectionForm/Races/useEditRace.tsx
frontend/src/components/ElectionForm/Settings.tsx
frontend/src/components/Elections.tsx
frontend/src/hooks/useAPI.ts
frontend/tsconfig.json

This cleans up references to the domain_model
It's only applied to the frontend, backend is harder since there are multiple domain_model folders that are used there

Use paths to clean up domain_model references

---

backend/src/Models/serialize-parameters/serialize-parameters-plugin.ts
backend/src/Models/serialize-parameters/serialize-parameters-transformer.ts

Removes .js file extension from relative imports that were breaking dev server (nodemon) since it is looking at the files in src (.ts) and not in build dir (.js).
None listed though this seems to be a recurring sticking point when folks are following the dev onboarding which suggests using `npm run dev`. It's not strictly necessary since folks can use `npm run build && npm run start`, but might be nice to be able to directly pickup backend changes during dev without restarting the server.

fix: remove file extensions from relative imports

---

backend/src/Tabulators/AllocatedScore.ts
backend/src/Tabulators/Approval.test.ts
backend/src/Tabulators/Approval.ts
backend/src/Tabulators/IRV.ts
backend/src/Tabulators/Plurality.ts
backend/src/Tabulators/RankedRobin.ts
backend/src/Tabulators/Star.ts
backend/src/Tabulators/Util.ts
domain_model/ElectionSettings.ts
domain_model/ITabulators.ts
frontend/src/components/Election/Results/Results.tsx

This updates the approval results page to sometimes indicate that the election is tied instead of showing a winner
Here are the specific updates
* Add election setting for breaking ties randomly
* Adjust results title to show ties
* Refactor tabulator to avoid managing offsets on an array
* Refactor tabulator to always sort candidates and break ties randomly (the break ties randomly setting is only used by the frontend)
* Refactor tabulator with SingleWinnerApproval sub-method
Here's some follow up tasks
* filter random tie break out of the detailed steps if random tiebreaker isn't enabled
* add support for random tie breaker in the settings (it's currently locked to disabled)
related #415

Add tie result for approval

---

backend/sample.env
docs/contributions/1_local_setup.md

After completing onboarding, making some changes to doc to reflect current setup process.  I made some assumptions here:
* We don't need/want any legacy (pre-azure) env vars
* We don't need to get keycloak creds directly since we're using the shared dev creds from the doc
https://github.com/Equal-Vote/star-server/issues/425

fix: update dev setup docs and default env vars

---

backend/src/Controllers/getElectionsController.ts
backend/src/Models/ElectionRolls.ts
docs/contributions/Infrastructure/11_keycloak_configuration.md
frontend/src/components/AuthSessionContextProvider.tsx
frontend/src/components/Elections/ElectionInvitations.tsx
frontend/src/components/Elections/ElectionsYouVotedIn.tsx
frontend/src/components/Header.js
frontend/src/hooks/useAPI.ts

* Update getElections to seperate unsubmitted and submitted votes
* Add "your account" button that takes you to the keycloak account console
* Avatars: I looked into this but hit some complications. It's probably not worth it pre-beta (more details #447)
* Voter Roll Logic: Current voters get added to rolls as a side effect of getElection. As a result your ip get's readded to the featured elections every time your on a new device. This causes the unsubmitted ballot and submitted ballot views to have identical entries even though the queries are correct (more details #449)
fixes #446

Add view account to navbar and separate invitations and previous elections pages 

---

docker-compose.yml
docs/contributions/1_local_setup.md

Adds some documentation on how to spin up postgres database and keycloak server locally.
For a follow up task, it's possible to export a keycloak configuration as a file, we should export a version with the main setup steps already done to minimize setup time.
I have been having issues getting the local database to connect to the local server on my desktop, but seems to work on my laptop following the same steps. So test it out and let me know if it works for you.
#425

Documenting starting up DB with docker

---

frontend/src/components/Election/Results/STAR/STARResultSummaryWidget.tsx

I noticed the mobile view on some elections cut off the names, so I set a max on the y axis width

Add max width for results yaxis

---

LICENSE

The information in this write up is based on a very short dive into the topic. My definitions are base on how I understand the licenses but please correct me if I'm wrong
Vision: I want the star elections project to exist as a true open source project, but I also want private companies to have a clear reference point for implementing STAR without fear of legal issues.
Hence I suggest we have the star-server repo use an AGPL-3.0 license, and have the starpy repo using MIT. This will keep star-server open source, but allow private companies to freely use starpy if they're looking for a reference implementation. 
* **AGPL-3** : This is the new standard for open source. The GPL family has strong copy-left protections which ensure that all derivatives must also be open source. AGPL also fixes …

Add AGPL-3 license

---

.github/workflows/node.js.yml

On my previous PR, the PR tests pass, but then it failed when running the deployment script. 
This PR adds another build script so the PR tests can catch more things
Previous deployment failure: https://github.com/Equal-Vote/star-server/actions/runs/8312718247/job/22747880307
Error when running locally: (looks like the PR was specifically missing errors on the frontend)
```
$ npm run build -ws
> shared@1.0.0 build
> tsc --project ./
> backend@1.0.0 build
> tsc --project ./
> star-vote@0.1.0 build
> tsc && vite build
src/components/Election/Results/STAR/STARResultSummaryWidget.tsx:69:13 - error TS2322: Type 'string' is not assignable to type 'number'.
69             votes: '', // this is making typescript unhappy, but it seems to work
~~~~~ …
```

Add extra step to catch more errors during PR

---

packages/frontend/src/components/Election/Admin/ViewBallot.tsx
packages/frontend/src/components/Election/Election.tsx
packages/frontend/src/components/Election/Results/Results.tsx
packages/frontend/src/components/Election/Results/ViewElectionResults.tsx
packages/frontend/src/components/Election/Sidebar.tsx
packages/frontend/src/components/Footer.tsx
packages/frontend/src/components/Header.tsx
packages/frontend/src/components/util.jsx
packages/frontend/src/index.css

When printing the results page this change hides any irrelevant details
NOTE: as shown in the video it's still possible for the results to break, but that can be fixed for now by changing the scaling of the print
https://github.com/Equal-Vote/star-server/assets/9289903/6005720a-04b2-4d3a-9ea8-2b5ea9668506

Make results page more print friendly

---

.github/workflows/build-push-deploy.yml

star-server-infra is now obsolete so we can remove it from the build workflow

Remove reference to star-server-infra in workflow

---

packages/frontend/src/components/Election/Admin/AdminHome.tsx
packages/frontend/src/components/ElectionForm/CreateElectionDialog.tsx
packages/frontend/src/components/ElectionForm/Details/ElectionAuthForm.tsx
packages/frontend/src/components/ElectionForm/ElectionSettings.tsx
packages/frontend/src/i18n/en.yaml

Sets device id as default option when creating open access elections
Adds Voter Authentication form to admin page
Adds Publicly Searchable setting to settings form
Removes view voters button from open access elections
Voter Authentication form, only visible in open access elections
Publicly Searchable
closes #461 and #471 
closes #560 and #597

Admin settings

---

packages/frontend/src/components/Election/Admin/ViewBallots.tsx

Putting the race titles in the candidate cells made the table too wide. This adds a row above candidates with the race titles, races span multiple columns. The default MUI tables don't have cell borders so I added borders to the races to make it clear, but I don't really like how it looks. Maybe ok for now.
closes #562

Adding race titles above candidates in ballot table

---

packages/frontend/src/components/Header.tsx
packages/frontend/src/components/LandingPage/LandingPageFeatures.tsx
packages/frontend/src/i18n/en.yaml

The logo is now in the center of the screen (previously it was centered between the left/right elements)

Center the header

---

packages/frontend/src/components/Elections/ElectionsYouManage.tsx
packages/frontend/src/components/Elections/ElectionsYouVotedIn.tsx
packages/frontend/src/components/Elections/OpenElections.tsx
packages/frontend/src/components/EnhancedTable.tsx
packages/frontend/src/components/util.tsx

Adds the "update_date" election field and adds it to the election tables and makes it the default sort method. 
Adds local time zones to table header.
Fixes a bug with date formatting. It was trying to pass the entire election object into the formatter as the time zone which was making all dates "Invalid Datetime".
Temporarily fixes bug with date sorting. The table sorting function sorts based on already formatted data, so dates were sorting by their string version which led to many issues. Now the comparator function is passed a isDate parameter that tells the comparator to convert back to dates and then to integers. I hate this solution and myself for implementing it, but it works until I fix the table to sort and then format data.

Adding "Last Updated" to election tables and fixing table date bugs

---

packages/frontend/src/components/ElectionForm/CreateElectionDialog.tsx
packages/frontend/src/components/ElectionForm/QuickPoll.tsx
packages/frontend/src/i18n/en.yaml

Fixes links in footer. When using links in en.yaml, the url has to include "http://www.", otherwise it sees it as page on the current site. 
Another note, it doesn't look like its possible to insert a target="_blank" in the yaml file to open the page in a new tab. We should figure out a workaround at some point.
Edit: 
Turning off random candidate order by default
closes #610
closes #621

Fixing links in footer, disabled random candidate order as default

---

packages/frontend/src/components/Election/Voting/RankedBallotView.jsx
packages/frontend/src/components/Election/Voting/VotePage.tsx
packages/frontend/src/components/ElectionForm/CreateElectionDialog.tsx
packages/frontend/src/components/ElectionForm/ElectionSettings.tsx
packages/frontend/src/components/LandingPage/LandingPageHero.tsx
packages/shared/src/domain_model/ElectionSettings.ts

Admins have the option of limiting the amount of ranks on a ranked ballot to a number between 3 and 8. If no option is selected, the MAX_BALLOT_RANKS environment variable will be used instead
https://github.com/user-attachments/assets/4ce376e9-9821-43fe-96b0-e4e69da03fa5
to close issue #645

Admin can now set rank limits in ranked ballots

---

packages/frontend/src/components/Election/Admin/ViewBallots.tsx

The simplest solution seemed to just add the DraftWarning component to indicate that these are test ballots. 
> to close issue #634

Issue #634 differentiate between test ballots and real ballots

---

packages/frontend/src/components/Election/Results/Results.tsx
packages/frontend/src/i18n/en.yaml
packages/frontend/src/index.css

Adds widgets for STAR PR using existing components.
First widget is a round by round bar chart with a pagination button to navigate rounds.
Second widget is a basic table showing all the round scores. 
This doesn't do any special highlighting because the existing components don't work for multi winner highlighting.

Adding Basic STAR PR widgets

---

packages/frontend/src/components/Election/Results/Results.tsx
packages/frontend/src/components/util.tsx

Here's the new final runoff graph for RCV. 
RCV continues to eliminate candidates until one of them has a relative majority. Previously it would only handle cases where there were 2 candidates in the final round, but now it can handle any number of candidates
Also add the <1% to make it more clear whether candidates were being rounded to 0%.
fixes #701
fixes #702

Add <1% and include all rcv runoff candidates

---

packages/backend/src/Controllers/Election/getElectionResultsController.ts
packages/backend/src/Tabulators/AllocatedScore.test.ts
packages/backend/src/Tabulators/AllocatedScore.ts
packages/backend/src/Tabulators/ParseData.ts
packages/frontend/src/components/Election/Results/Results.tsx

This PR addresses a split point issue and abstentions
This addresses an of by one error when selecting the split point.
Currently after Marge is elected in [the Simpsons election](https://bettervoting.com/frmcv6/results) the log outputs
```
The 5 voters who gave Marge Simpson 5 stars are partially represented and will be reweighted by 1.12 for future rounds.
```
This is incorrect since a split point at 5 stars is not enough to fill the quota. (There are 5 voters who gave her 5 stars, but the quota is 5.6)
The split point should be set based on the first ballot to exceed the quota, however it current sets the split point based on the last ballot before exceeding the quota. 
Here's the updated log after the fix
```
The 5 voters who gave Marge Simpson more than 4 stars are fully represented …
```

Fix edge case for single fractional surplus

---

packages/frontend/index.html
packages/frontend/src/components/LandingPage.tsx
packages/frontend/src/components/LandingPage/LandingPageHero.tsx
packages/frontend/src/components/LandingPage/LandingPagePricing.tsx
packages/frontend/src/components/LandingPage/LandingPageStats.tsx
packages/frontend/src/components/LandingPage/LandingPageTestimonials.tsx
packages/frontend/src/theme.tsx

- Removed *huge* gap value.
Old:
New:

10 21 decrease gaps between elements in the landing pages

---

packages/frontend/src/index.css

If a word is too long to fit in a visible block that contains it, with this change, the browser will break the word across lines. The problem of this not happening was noticed particularly with election names; however, the present proposed solution applies very broadly, probably to all messages the app displays. Technically, it applies to everything in CSS class "MuiTypography-root", which is probably everything.
I'm not sure whether the location of the new declaration is appropriate. Prior, there were no "Mui"- declarations there, and I may be abusing the intended pattern for administering a project's use of the Material User Interface (MUI) library.
Intended to resolve #485.

fix: break any long word across lines.

---

packages/frontend/src/components/Election/Results/components/ResultsBarChart.tsx

Adds a tick margin to the equal preferences results bar chart when equal preference votes are all zeroes to fix overlapping text.
Closes #756

Fix: results bar chart equal preference all zeroes

---

packages/frontend/src/i18n/en.yaml

Correct typos 'acessible' and 'mutiple' that had been showing up in the page footer. Corrects #801.

Typos 'acessible' and 'mutiple'

---

packages/frontend/src/components/ElectionForm/Races/AddRace.tsx
packages/frontend/src/components/ElectionForm/Races/Race.tsx
packages/frontend/src/components/ElectionForm/Races/RaceDialog.tsx
packages/frontend/src/components/ElectionForm/Races/RaceForm.tsx

Let's say you go to add a race to an election you are working on, and let's say you go through the stepper to set the election type. Then you commit that change to add the race for real. Then say you go to add another race. The dialog would open with the stepper still on the second step.
When you open the racial dialog for the second time, the stepper is reset to the first step.
I don't want to shoot my screen.
Fixes #729 .

Reset stepper in racial dialog every time it is closed

---

packages/frontend/src/App.tsx
packages/frontend/src/components/LandingPage.tsx

- Added  `/Feedback` route that loads the Landing Page.
- Implemented automatic Feedback dialog popup trigger when navigating to `/Feedback` .
- Ensured existing Feedback button functionality remains unchanged.
- Video : https://youtu.be/7p3fTh13p0o
- Tested locally to confirm that visiting `/Feedback` opens the feedback popup.
- Verified that clicking the Feedback button still works as expected.
Closes #799

feat: add direct URL support for opening Feedback popup

---

packages/frontend/package.json
packages/frontend/src/App.tsx
packages/frontend/src/components/NameMatchingTester.tsx

Working towards write in candidate [feature ](https://docs.google.com/presentation/d/1UfHdymfJH48uJNrIBbqz64EXwz_ukcz8MVoxXPZmg-c/edit?usp=sharing)
Adds page to test fuzzy name matching and clustering
Also has drag and drop test but requires updating drag and drop library to support multiple containers

Adding fuzzy name matching test page

---

packages/frontend/src/components/ElectionForm/Races/RaceForm.tsx

Removes fixed height from part of race form, but at the cost of a height transition. The opacity transition remains.
fixes #842

Free height of part of race form

---

packages/frontend/src/i18n/en.yaml

Added a "-" and a "." on about page that were missing.

Fixed Punctuation on About Page

---

packages/frontend/src/components/Election/Voting/VotePage.tsx

Ballots with mix of zeros and blanks no longer count as abstention
Ballots with mix of zeros and blanks should not count as abstention. This fixes the immediate issue but also raises another issue of votes left blank should not be counted as '0'.

Issue #754: Abstention Issue

---

packages/frontend/src/i18n/es.yaml

I updated the es.yaml file to have a full Spanish translation. I didn't translate "Ranked Robin" because there is not a direct translation other than "Todos contra todos con orden de preferencia" or "Votación por orden de preferencia en formato todos contra todos" which is basically explaning that all candidates are paired in one-on-one match-ups. I left it as "Ranked Robin" for the time being. In baseball, and sports, we use in "Round Robin" in English to signal that they are 1 on 1 match-ups so I believe most of Spanish speakers will get the idea.

Update Spanish translations for ballot submission and voting instructions.

---

packages/frontend/src/components/About.tsx
packages/frontend/src/components/Footer.tsx

This PR fixes the issue where the Link in footer and About page open in same tab.
Video of footer
https://www.loom.com/share/b6eaffdedb6646a8a9ce1365681d4a02?sid=3dc07305-01a1-4e8d-82e6-bd7f586b732b Be sure to include both desktop and mobile views (mobile could be as low as 320 px wide) 
🔗 Related Issue
Closes #937

Fix: Open external link in new tab (Issue #937)

---

packages/frontend/src/components/Election/Voting/GenericBallotView/CandidateLabel.tsx
packages/frontend/src/components/ElectionForm/CreateElectionDialog.tsx

Issue #745 asked to eliminate the "continue" button on the first step when creating a New Election. @ArendPeter also suggested that I added like a quarter of a second to make the transition to next step smoother.

Fixing #745 I eliminated the "continue" button

---

packages/frontend/src/components/Election/DraftWarning.tsx
packages/frontend/src/components/Election/ElectionStateWarning.tsx
packages/frontend/src/components/Election/Voting/VotePage.tsx
packages/frontend/src/i18n/en.yaml

Addresses the bug noted [here](https://github.com/Equal-Vote/bettervoting/issues/891), that users aren't made aware that the election they are voting in is archived until they attempt to submit their vote.
Changes:
- The submit button is disabled when the election is archived
- A warning card is provided above the election when the election is archived (in the same style as the draft warning)
- The `DraftWarning` component has been consolidated into a more modular component `ElectionStateWarning`, which `DraftWarning` is a concrete implementation of, along with the new "Election is archived" warning.
``fixes #891``

fix: warn when trying to vote in archived election
